import pandas as pd
import numpy as np

def cleaner(df):
    df.drop(columns=['TRAILING_LOAD_AFFECTED', 'TIMING_LOAD_AFFECTED', 'FINANCIAL_YEAR_AND_PERIOD',
                     'END_STANOX', 'START_STANOX','PLANNED_ORIG_LOC_CODE_AFF', 'INCIDENT_NUMBER','PLANNED_ORIG_GBTT_DATETIME_AFF','PLANNED_DEST_GBTT_DATETIME_AFF',
                     'PLANNED_DEST_LOC_CODE_AFFECTED', 'INCIDENT_START_DATETIME', 'INCIDENT_END_DATETIME',
                     'SECTION_CODE', 'ATTRIBUTION_STATUS', 'INCIDENT_EQUIPMENT', 'INCIDENT_DESCRIPTION',
                     'TRAIN_SCHEDULE_TYPE_AFFECTED', 'INCIDENT_RESPONSIBLE_TRAIN', 'EVENT_DATETIME', 'RESP_TRAIN',
                     'REACT_TRAIN', 'NETWORK_RAIL_LOCATION_MANAGER', 'OPERATOR_AFFECTED', 'ORIGIN_DEPARTURE_DATE',
                     'INCIDENT_REASON_DESCRIPTION', 'INCIDENT_CREATE_DATE'], inplace=True)

    df = df[df['TRAIN_SERVICE_CODE_AFFECTED'] != 22216001.0]

    return df
